load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_Core"
   ,  srcs       = ["aapFunctionalCluster_Core.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
#           "interface_CommunicationManagement_VerificationStatusConfigurationByDataId.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

